version: '3.8'

services:
  reporting:
    container_name: evidently_reporting
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - ./artifacts:/artifacts
    ports:
      - "8082:8082"
