version: "3.8"

services:
  reporting:
    container_name: evidently-report
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"  # Serveur HTTP pour le fichier HTML
    volumes:
      - ../data:/data
      - ./reports:/reports
    restart: always
