version: "3.8"

services:
  reporting:
    container_name: evidently-report
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ../data:/data
      - ./reports:/reports  # Volume pour sauvegarder le rapport localement
    restart: always
