version: '3.8'

networks:
  shared_net:
    driver: bridge

services:
  serving-api:
    container_name: serving-api
    build:
      context: .
      dockerfile: Dockerfile
    # On remplace le volume nommé par un bind mount "classique"
    volumes:
      - ../data:/data
      - ../artifacts:/artifacts
    ports:
      - "8080:8080"
    networks:
      - shared_net
    restart: always
