version: '3.8'

networks:
  shared_net:
    external: true

volumes:
  data_shared:

services:
  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data_shared:/data
    ports:
      - "8081:8081"
    networks:
      - shared_net
    restart: always
